apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kotlin-upper
  namespace: argocd
spec:
  project: kotlin
  source:
    repoURL: https://github.com/ajmal-amirzad/argo-cd.git
    targetRevision: infra
    path: helm
    helm:
      valueFiles:
      - values-upper.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: upper
  syncPolicy:
    automated:
      enabled: false