apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.deployment.name }}-{{ .Values.deployment.namespace }}
  namespace: {{ .Values.deployment.namespace }}
  labels:
    app: {{ .Values.deployment.name }}
automountServiceAccountToken: true